apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret  # the name of the secret config file
                key: mongo-root-username  # the key of the secret in the data part of the secret config file
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret  # the name of the secret config file
                key:  mongo-root-password  # the key of the secret in the data part of the secret config file
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb  # the label of deployment and pod
  # default type: ClusterIP -> internal port
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017